### ISSUE TITLE
Answers to the review questions for midterm exam

### ISSUE THREAD

**Issue by jerry-shijieli** [imaginationsuper/CSC510ReviewForFinal#1]
Hi All @azhe825 @dichen001 @amritbhanu  

I just uploaded the answers to the review 1-7 on course website for the midterm exam. The review 8 is still in progress. Please feel free to correct the mistakes or update the answers with more details. Happy Spring Break and Good Luck with the Midterm! Thanks!

**Comment by dichen001** [comment]
Thanks man! It's really helpful! :+1: :clap:
